# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code
name: Build Step

on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "runnigngngngngn"

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    needs: ["build", "test-stage"]

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          tags: |
            lionel411/bara-api:${{ github.sha }} 
            ghcr.io/lionel411/bara-api:${{ github.sha }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ["build-and-push-docker-image"]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{secrets.ORGANIZATION}}/gitops-bara-infra
          ref: "main"
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email ${{secrets.G_USER_EMAIL}}
          git config --global user.name ${{secrets.G_USER_NAME}}
          echo ${{ github.sha }}
          sed -i "s#${{secrets.DOCKER_USER}}.*#${{secrets.DOCKER_USER}}/bara-api:${{ github.sha }}#g" api-deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
